artifacts_root: artifacts

data_ingestion:
 root_dir: artifacts/data_ingestion
 local_file: data/train.csv

data_validation:
  root_dir: artifacts/data_validation
  local_file: data/train.csv
  validation_status_path: artifacts/data_validation/status.txt