id: int
item_type: object
weight_grams: float
height_cm: float
width_cm: float
depth_cm: float
primary_material: object
secondary_material: object
gem_type: object
gem_count: int
primary_color: object
surface_texture: object
rarity_level: object
origin_culture: object
creation_year: float
has_inscription: int
inscription_script: object
pattern_type: object
craftsmanship_level: object
magic_enchanted: int
environment_type: object
oxidation_level: object
restoration_status: object
authentication_status: object
monetary_value_gold: float
historical_significance: object
cursed_status: int
shine_factor: float
damage_resistance: float
set_piece: int
description: object
preservation_score: float